### ISSUE TITLE
使用1panel安装的Xboard，安装目录下找不到public文件夹

### ISSUE THREAD

**Issue by Maybe404** [cedar2025/Xboard#121]
使用1panel安装的Xboard，安装目录下找不到public文件夹，在哪里更换主题文件呢

**Comment by cedar2025** [comment]
1、在项目目录创建 public/theme/ 目录并将主题放入到此目录下
2、修改docker-compose.yaml文件， 在volumes:中增加 ```- ./public/theme/主题目录/:/public/theme/主题目录/```
3、重启xboard
```
docker compose down 
docker compose up -d
```
示例docker-compose.yaml 文件 （假设主题目录为customTheme） 
```
version: '3'
services:
  xboard:
    image: ghcr.io/cedar2025/xboard:latest
    volumes:
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.docker/.data/
      - ./public/theme/customTheme/:/www/public/theme/customTheme/
      # - ./config/v2board.php:/www/config/v2board.php
      - redis-socket:/run/redis-socket # 挂载socket
    environment:
      - docker=true #用于给安装脚本判断是否为docker环境
    depends_on:
      - redis
    network_mode: host
    restart: always
  redis:
    build: 
      context: .docker/services/redis
    restart: always
    volumes:
      - ./.docker/.data/redis:/data/ # 挂载redis持久化数据
      - redis-socket:/run/redis-socket # 挂载socket
volumes:
  redis-socket:
```
