### ISSUE TITLE
[BUG] 在k8s里面选择sqlite初始化的时候，创建出来的 database.sqlite 的组用户是root，导致php的组用户（www） 没有权限写入数

### ISSUE THREAD

**Issue by Tomyail** [cedar2025/Xboard#158]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------

Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------

是

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xboard
  template:
    metadata:
      labels:
        app: xboard
    spec:
      containers:
      - name: xboard
        image: ghcr.io/cedar2025/xboard:latest
        ports:
        - containerPort: 7001


---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379


---

```

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

XBOARD初始化失败SQLSTATE[HY000]: GENERAL ERROR: 8 ATTEMPT TO WRITE A READONLY DATABASE (CONNECTION: SQLITE, SQL: INSERT INTO "V2_SETTINGS" ("NAME", "VALUE", "UPDATED_AT", "CREATED_AT") VALUES (THEME_XBOARD, {"THEME_COLOR":"DEFAULT","BACKGROUND_URL":"","CUSTOM_HTML":""}, 2024-06-24 20:08:27, 2024-06-24 20:08:27))

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Run the php artisan log:export 7 command to export log files (where 7 represents logs for the last 7 days).
运行`php artisan log:export 7` 命令导出的日志文件(其中7为最近7天的日志)。
--------
