### ISSUE TITLE
Maintain backward compatibility for the Proxy-Group node matching logic in Protocol/ClashMeta

### ISSUE THREAD

**Issue by JobberRT** [cedar2025/Xboard#397]
In previous versions of XBoard (I forgot which version, but it was before the new admin UI went live), the node matching logic for clash's proxy-groups was: check if it was a regex match, if not, perform a string match. And if the `proxies` field was an empty array ([]), all nodes would be added to the proxies of the current proxy-group. Examples are as follows:
```yaml
# Suppose there are three proxies: Proxy#1/Proxy#2/Proxy#3

proxy-groups:
  # This group's outcome is [Proxy#1, Proxy#2]
  - name: "With Custom Proxy/ProxyGroup"
    type: "select"
    proxies:
      - "Proxy#1"
      - "Proxy#2"
  # This group's outcome is [Proxy#1, Proxy#2, Proxy#3]
  - name: "Empty Group"
    type: "url-test"
    url: "https://cp.cloudflare.com"
    interval: 10
    tolerance: 200
    lazy: true
    proxies: []
```

However, now XBoard will ignore the condition "if the proxies of a proxy-group are an empty array", and add all nodes to each proxy-group. The example is as follows:
```yaml
# Suppose there are three proxies: Proxy#1/Proxy#2/Proxy#3

proxy-groups:
  # This group's outcome is [Proxy#1(matched name), Proxy#2(matched name), #Proxy#3(unnecessary added proxy)]
  # While Proxy#3 should not be here
  - name: "With Custom Proxy/ProxyGroup"
    type: "select"
    proxies:
      - "Proxy#1"
      - "Proxy#2"
      
  # This group's outcome is [Proxy#1, Proxy#2, Proxy#3]
  - name: "Empty Group"
    type: "url-test"
    url: "https://cp.cloudflare.com"
    interval: 10
    tolerance: 200
    lazy: true
    proxies: []
```

Right now my workaround is change the code from
https://github.com/cedar2025/Xboard/blob/c45c2b9abad2e92fb8bf2fa497964c31c290385d/app/Protocols/ClashMeta.php#L97-L99

to 

```php
if (empty($config['proxy-groups'][$k]['proxies'])) {
  $config['proxy-groups'][$k]['proxies'] = array_merge($config['proxy-groups'][$k]['proxies'], $proxies);
}
```
