### ISSUE TITLE
[Example] XrayR config example for XBoard REALITY

### ISSUE THREAD

**Issue by JobberRT** [cedar2025/Xboard#73]
## Before use `XrayR`
- As for 2024-02-01, `XrayR`'s latest version is `v0.9.2`, and it has a bug that will cause querying the `UniProxy` api with wrong `node_type` if you are using `vless+reality`. And that bug is fixed but `XrayR` hasn't release a new version yet. You have to build your own executable based on the latest `master` branch. See [This issue for detail](https://github.com/XrayR-project/XrayR/issues/598)
- `XrayR`'s install bash script it not complete/most updated, make sure you visit their doc webiste to see the latest correct configuration.

## Example
```yaml
Log:
  Level: "debug" # Log level: none, error, warning, info, debug
  AccessPath: "/etc/XrayR/access.log"
  ErrorPath: "/etc/XrayR/error.log"
DnsConfigPath: "/etc/XrayR/dns.json" # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: "/etc/XrayR/route.json" # Path to route config, check https://xtls.github.io/config/routing.html for help
OutboundConfigPath: "/etc/XrayR/custom_outbound.json" # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 5 # Handshake time limit, Second
  ConnIdle: 15 # Connection idle time limit, Second
  UplinkOnly: 5 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 5 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 256 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "NewV2board" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel
    ApiConfig:
      ApiHost: "https://example.com"
      ApiKey: "somesecret"
      NodeID: 1
      NodeType: "V2ray" # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
    ControllerConfig:
      ListenIP: "0.0.0.0" # IP address you want to listen
      SendIP: "0.0.0.0" # IP address you want to send pacakage
      UpdatePeriodic: 5 # Time to update the nodeinfo, how many sec.
      EnableDNS: true # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: UseIPv4 # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      
      # +-------------------------------------+
      # | Below are the real important config |
      # +-------------------------------------+
      DisableLocalREALITYConfig: true  # disable local reality config
      # I just minified this block
      REALITYConfigs:
        Show: true # Show REALITY debug
      # And this block too
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
```
